# Generated by Django 5.2.3 on 2025-06-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='broadcasts/photos/', verbose_name='Фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='broadcasts/videos/', verbose_name='Видео')),
                ('audio', models.FileField(blank=True, null=True, upload_to='broadcasts/audios/', verbose_name='Аудио')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Разослано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Аккаунт')),
            ],
        ),
    ]
