# Generated by Django 5.2.3 on 2025-06-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
