# Generated by Django 5.2.3 on 2025-06-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botpanel', '0002_alter_botmessage_options'),
        ('telegram_broadcast', '0002_alter_broadcast_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='message_to_forward',
            field=models.ForeignKey(blank=True, help_text='Сообщение, которое будет разослано', null=True, on_delete=django.db.models.deletion.SET_NULL, to='botpanel.botmessage'),
        ),
    ]
