# Generated by Django 5.2.3 on 2025-06-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botpanel', '0002_alter_botmessage_options'),
        ('telegram_broadcast', '0003_broadcast_message_to_forward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='message_to_forward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botpanel.botmessage', verbose_name='Сообщение, которое будет разослано'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
