# Generated by Django 5.2.3 on 2025-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_broadcast', '0004_alter_broadcast_message_to_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_video_note',
            field=models.BooleanField(default=False, help_text='Отправить как видеосообщение (кружок)'),
        ),
    ]
