# Generated by Django 5.2.3 on 2025-07-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_broadcast', '0005_broadcast_is_video_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_voice_note',
            field=models.BooleanField(default=False, help_text='Отправить как голосовое сообщение'),
        ),
    ]
