# Generated by Django 5.2.3 on 2025-07-22 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_alter_groupuser_options_and_more'),
        ('telegram_broadcast', '0006_broadcast_is_voice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='Участникам какой группы?'),
        ),
    ]
