# Generated by Django 5.2.3 on 2025-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_broadcast', '0007_broadcast_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='is_video_note',
            field=models.BooleanField(default=False, help_text='Отправить как видеосообщение (кружок)', verbose_name='Видео (кружок)'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='is_voice_note',
            field=models.BooleanField(default=False, help_text='Отправить как голосовое сообщение', verbose_name='Голосовое (только .ogg)'),
        ),
    ]
