# Generated by Django 5.2.3 on 2025-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('hint', models.CharField(blank=True, help_text='Для себя', max_length=255, verbose_name='Подсказка')),
            ],
            options={
                'verbose_name': 'Телеграм-бот',
            },
        ),
    ]
