# Generated by Django 5.2.3 on 2025-06-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmessage',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
    ]
