# Generated by Django 5.2.3 on 2025-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botpanel', '0003_botmessage_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='is_video_note',
            field=models.BooleanField(default=False, help_text='Отправить как видеосообщение (кружок)'),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='video',
            field=models.FileField(blank=True, help_text='Видеофайл (mp4 и др.)', null=True, upload_to='videos/'),
        ),
    ]
