# Generated by Django 5.2.3 on 2025-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botpanel', '0004_botmessage_is_video_note_botmessage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessage',
            name='text',
            field=models.TextField(blank=True, help_text='Текст сообщения', null=True),
        ),
    ]
