# Generated by Django 5.2.3 on 2025-06-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupuser',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники групп'},
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group', 'user_id')},
        ),
    ]
